// <auto-generated />
namespace ClassLibrary1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class UndoGuid : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UndoGuid));
        
        string IMigrationMetadata.Id
        {
            get { return "202104242001025_Undo-Guid"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
